version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: booksuser
      POSTGRES_PASSWORD: bookspass
      POSTGRES_DB: booksdb
    ports:
      - "5432:5432"
    volumes:
      # - dbdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    restart: unless-stopped

  frontend:
    build: ./client
    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=booksuser
      - DB_PASSWORD=bookspass
      - DB_NAME=booksdb

volumes:
  dbdata: