version: "3.8"
services:
  frontend:
    build: ./client
    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - "3000:3000"
  # Távolítsd el a teljes kötést, hogy a konténer saját /app mappáját használja a buildelt fájlokkal
  # volumes:
  #   - .:/app
  #   - /app/node_modules